name: canfar - multi-cloud astronomy data processing
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
relative_permalinks: false
markdown: kramdown
repository: https://github.com/canfar
help_url: /docs/help
url: http://canfar.github.io/
description: Process astronomy data on the cloud
login: http://www.canfar.phys.uvic.ca/canfar/login.html
